name: Python Lint & Syntax Check

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Syntax check
        run: |
          # Fail if there are syntax errors
          python -m compileall -q .

      - name: Run flake8
        run: |
          flake8 .
